version: "3"

services:
  openwhisk:
    container_name: openwhisk_container
    image: openwhisk/standalone:nightly
    restart: always
    environment:
      TZ: "Asia/Seoul"
    ports:
      - "3232:3232"
      - "3233:3233"
    networks:
      - mynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  mynet:
    driver: bridge