name: deploy

on:
  push:
    branches: [ main ]
   
permissions:
  contents: read

jobs:
  deploy:
    needs: build  
    runs-on: ubuntu-latest  # 이 작업은 최신 Ubuntu 러너에서 실행됩니다.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SCP docker compose file
        uses: appleboy/scp-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose.yml"
          target: ~/docker-compose
          strip_components: 1

      - name: Docker compose up
        uses: appleboy/ssh-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker-compose -f ~/docker-compose/docker-compose.yml pull
            docker-compose -f ~/docker-compose/docker-compose.yml down
            docker-compose -f ~/docker-compose/docker-compose.yml up -d